alerts:
- rule: DEPLOYMENT_FAILED
- rule: DOMAIN_FAILED
envs:
- key: REDIS_HOST
  scope: RUN_AND_BUILD_TIME
  value: redis-abc.db.ondigitalocean.com
- key: REDIS_PORT
  scope: RUN_AND_BUILD_TIME
  value: "25061"
- key: REDIS_USERNAME
  scope: RUN_AND_BUILD_TIME
  value: default
- key: REDIS_PASSWORD
  scope: RUN_AND_BUILD_TIME
  value: yourPASSWORD
name: fsms-app
region: fra
services:
- dockerfile_path: /frontend/Dockerfile
  github:
    branch: master
    repo: adnankaya/FullStack_MicroService_Digital_Ocean_App_Platform
  http_port: 80
  instance_count: 1
  instance_size_slug: basic-xxs
  name: fe
  routes:
  - path: /
  source_dir: frontend
- dockerfile_path: /service-app1/Dockerfile
  github:
    branch: master
    repo: adnankaya/FullStack_MicroService_Digital_Ocean_App_Platform
  http_port: 5000
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api1
  routes:
  - path: /app1
  source_dir: service-app1
- dockerfile_path: service-app2/Dockerfile
  github:
    branch: master
    repo: adnankaya/FullStack_MicroService_Digital_Ocean_App_Platform
  http_port: 5001
  instance_count: 1
  instance_size_slug: basic-xxs
  name: api2
  routes:
  - path: /app2
  source_dir: service-app2
workers:
- dockerfile_path: /worker-celery/Dockerfile
  github:
    branch: master
    repo: adnankaya/FullStack_MicroService_Digital_Ocean_App_Platform
  instance_count: 1
  instance_size_slug: basic-xxs
  name: celery
  source_dir: .